use std::{
    collections::{BTreeMap, BTreeSet},
    env,
    error::Error,
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
};

use apple_plist::Value;

const DEVELOPMENT_LOCALIZATION: &str = "en";

#[derive(Debug)]
struct Catalog {
    locale: String,
    type_name: String,
    values: BTreeMap<String, String>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let resources_dir = manifest_dir.join("resources");
    println!("cargo:rerun-if-changed={}", resources_dir.display());

    let catalogs = read_catalogs(&resources_dir)?;
    validate_catalogs(&catalogs)?;

    let generated = generate_catalogs(&catalogs)?;
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(out_dir.join("language_catalogs.rs"), generated)?;
    Ok(())
}

fn read_catalogs(resources_dir: &Path) -> Result<Vec<Catalog>, Box<dyn Error>> {
    let mut locales = Vec::new();
    for entry in fs::read_dir(resources_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }

        let directory_name = entry.file_name();
        let directory_name = directory_name.to_str().ok_or_else(|| {
            invalid_data(format!(
                "localization directory is not valid UTF-8: {}",
                entry.path().display()
            ))
        })?;
        let Some(locale) = directory_name.strip_suffix(".lproj") else {
            continue;
        };

        let strings_path = entry.path().join("Localizable.strings");
        if strings_path.is_file() {
            locales.push((locale.to_owned(), strings_path));
        }
    }
    locales.sort_by(|left, right| left.0.cmp(&right.0));

    if locales.is_empty() {
        return Err(invalid_data(format!(
            "no *.lproj/Localizable.strings files found under {}",
            resources_dir.display()
        ))
        .into());
    }

    let mut type_names = BTreeSet::new();
    locales
        .into_iter()
        .map(|(locale, path)| {
            println!("cargo:rerun-if-changed={}", path.display());
            let type_name = catalog_type_name(&locale)?;
            if !type_names.insert(type_name.clone()) {
                return Err(invalid_data(format!(
                    "localization {locale} produces duplicate Rust type {type_name}"
                ))
                .into());
            }
            Ok(Catalog {
                locale,
                type_name,
                values: read_strings(&path)?,
            })
        })
        .collect()
}

fn read_strings(path: &Path) -> Result<BTreeMap<String, String>, Box<dyn Error>> {
    let bytes = fs::read(path)?;
    let value: Value = apple_plist::from_slice(&bytes)?;
    let Value::Dictionary(dictionary) = value else {
        return Err(invalid_data(format!(
            "{} is not an Apple strings dictionary",
            path.display()
        ))
        .into());
    };

    dictionary
        .into_iter()
        .map(|(key, value)| {
            if !valid_key(&key) {
                return Err(invalid_data(format!(
                    "{} contains key {key:?}, which is not a Rust enum variant",
                    path.display()
                ))
                .into());
            }
            let Value::String(value) = value else {
                return Err(invalid_data(format!(
                    "{} contains non-string value for key {key:?}",
                    path.display()
                ))
                .into());
            };
            Ok((key, value))
        })
        .collect()
}

fn validate_catalogs(catalogs: &[Catalog]) -> Result<(), Box<dyn Error>> {
    let development = catalogs
        .iter()
        .find(|catalog| catalog.locale == DEVELOPMENT_LOCALIZATION)
        .ok_or_else(|| {
            invalid_data(format!(
                "development localization {DEVELOPMENT_LOCALIZATION:?} is missing"
            ))
        })?;
    let expected = development.values.keys().cloned().collect::<BTreeSet<_>>();

    for catalog in catalogs {
        let actual = catalog.values.keys().cloned().collect::<BTreeSet<_>>();
        if actual == expected {
            continue;
        }
        let missing = expected.difference(&actual).cloned().collect::<Vec<_>>();
        let extra = actual.difference(&expected).cloned().collect::<Vec<_>>();
        return Err(invalid_data(format!(
            "localization {:?} does not match {DEVELOPMENT_LOCALIZATION:?}; missing: {missing:?}; extra: {extra:?}",
            catalog.locale
        ))
        .into());
    }
    Ok(())
}

fn generate_catalogs(catalogs: &[Catalog]) -> Result<String, Box<dyn Error>> {
    let mut output = String::from("// @generated by build.rs; do not edit.\n\n");

    for (index, catalog) in catalogs.iter().enumerate() {
        writeln!(output, "#[derive(Debug)]")?;
        writeln!(output, "struct {}Catalog;", catalog.type_name)?;
        writeln!(
            output,
            "impl LanguageCatalog for {}Catalog {{",
            catalog.type_name
        )?;
        writeln!(output, "    fn identifier(&self) -> &'static str {{")?;
        writeln!(output, "        {:?}", catalog.locale)?;
        writeln!(output, "    }}")?;
        writeln!(output, "    fn text(&self, key: Key) -> &'static str {{")?;
        writeln!(output, "        match key {{")?;
        for (key, value) in &catalog.values {
            writeln!(output, "            Key::{key} => {value:?},")?;
        }
        writeln!(output, "        }}")?;
        writeln!(output, "    }}")?;
        writeln!(output, "}}")?;
        writeln!(
            output,
            "static CATALOG_{index}: {}Catalog = {}Catalog;\n",
            catalog.type_name, catalog.type_name
        )?;
    }

    writeln!(
        output,
        "static LANGUAGE_CATALOGS: &[&dyn LanguageCatalog] = &["
    )?;
    for index in 0..catalogs.len() {
        writeln!(output, "    &CATALOG_{index},")?;
    }
    writeln!(output, "];\n")?;

    let development_index = catalogs
        .iter()
        .position(|catalog| catalog.locale == DEVELOPMENT_LOCALIZATION)
        .ok_or_else(|| invalid_data("development localization disappeared during generation"))?;
    writeln!(
        output,
        "static DEVELOPMENT_CATALOG: &dyn LanguageCatalog = &CATALOG_{development_index};"
    )?;
    Ok(output)
}

fn catalog_type_name(locale: &str) -> Result<String, Box<dyn Error>> {
    let mut output = String::new();
    for segment in locale.split(|character: char| !character.is_ascii_alphanumeric()) {
        if segment.is_empty() {
            continue;
        }
        let mut characters = segment.chars();
        let first = characters
            .next()
            .ok_or_else(|| invalid_data(format!("invalid localization identifier {locale:?}")))?;
        output.push(first.to_ascii_uppercase());
        output.extend(characters);
    }
    if output.is_empty() || output.starts_with(|character: char| character.is_ascii_digit()) {
        return Err(invalid_data(format!("invalid localization identifier {locale:?}")).into());
    }
    Ok(output)
}

fn valid_key(key: &str) -> bool {
    let mut characters = key.chars();
    characters
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
        && characters.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn invalid_data(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message.into())
}
