[package]
name = "charme-macos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "charme"
path = "src/main.rs"

[dependencies]
charme-core = { path = "../../crates/charme-core" }
charme-renderer = { path = "../../crates/charme-renderer" }

[target.'cfg(target_os = "macos")'.dependencies]
cacao.workspace = true
core-graphics.workspace = true
foreign-types.workspace = true

[lints]
workspace = true
