[workspace]
resolver = "3"
members = [
    "apps/charme-macos",
    "crates/charme-application",
    "crates/charme-bevy",
    "crates/charme-core",
    "crates/charme-renderer",
    "crates/charme-shader",
]
default-members = ["apps/charme-macos"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[workspace.dependencies]
bevy = { version = "0.19.0", default-features = false }
bevy_pmx = { git = "https://github.com/umoho/bevy_pmx.git", rev = "9b7b90b02da76ba9ce6f1ad48e63a0384073ea35", default-features = false }
cacao = "0.3.2"
core-graphics = "0.22.3"
foreign-types = "0.3.2"
naga = { version = "29.0.3", features = ["wgsl-in"] }
# Enabling naga-oil's default `glsl` feature affects Bevy through Cargo feature
# unification and currently makes Bevy's built-in shader composition panic.
naga_oil = { version = "0.22.0", default-features = false }
nom = "8.0.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.20"
unicode-ident = "1.0.24"
url = "2.5.8"
uuid = { version = "1.18.1", features = ["serde", "v4"] }

[workspace.lints.rust]
missing_debug_implementations = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("cargo-clippy"))'] }

[workspace.lints.clippy]
all = "warn"
