name = "charme-macos"
productName = "Charme"
version = "0.1.0"
identifier = "com.umoho.charme"
formats = ["app"]
outDir = "target/release/bundle"
binariesDir = "target/release"
beforePackagingCommand = { script = "MACOSX_DEPLOYMENT_TARGET=11.0 cargo build --release -p charme-macos", dir = "." }
binaries = [{ path = "charme", main = true }]
category = "GraphicsAndDesign"
resources = [
  { src = "apps/charme-macos/resources/en.lproj", target = "en.lproj" },
  { src = "apps/charme-macos/resources/zh-Hans.lproj", target = "zh-Hans.lproj" },
]

[macos]
minimumSystemVersion = "11.0"
infoPlistPath = "apps/charme-macos/Info.plist"
