[package]
name = "charme-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = [
    "async_executor",
    "bevy_asset",
    "bevy_camera",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_image",
    "bevy_light",
    "bevy_mesh",
    "bevy_pbr",
    "bevy_render",
    "bevy_shader",
    "multi_threaded",
    "std",
] }
bevy_pmx.workspace = true
charme-bevy = { path = "../charme-bevy" }
charme-core = { path = "../charme-core" }

[lints]
workspace = true
