#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Locale {
    ZhCn,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Key {
    OpenProject,
    NewProject,
    StartupTitle,
    StartupSubtitle,
    StartupFormats,
    RecentProjects,
    ProjectFallback,
    Scene,
    EmptyScene,
    Materials,
    EmptyMaterials,
    Inspector,
    InspectorBody,
    Brightness,
    RendererStarting,
    ProjectOpened,
    WaitingCharacter,
    LoadingMaterials,
    LoadingPmxTextures,
    InspectingShader,
    ShaderError,
    ReflectionFailed,
    MaterialInspector,
    WgslShader,
    NoMaterials,
    ErrorPrefix,
    ChooseProjectMessage,
    ChoosePmxMessage,
    ChooseShaderMessage,
    FileMenu,
    OpenProjectMenu,
    NewProjectMenu,
    ImportPmxMenu,
    InspectShaderMenu,
    EditMenu,
    ViewMenu,
    WindowMenu,
}

pub(crate) fn current() -> Locale {
    Locale::ZhCn
}

pub(crate) fn text(key: Key) -> &'static str {
    match (current(), key) {
        (Locale::ZhCn, Key::OpenProject) => "打开项目",
        (Locale::ZhCn, Key::NewProject) => "新建项目",
        (Locale::ZhCn, Key::StartupTitle) => "开始使用Charme",
        (Locale::ZhCn, Key::StartupSubtitle) => "打开或新建一个项目以开始编辑角色材质",
        (Locale::ZhCn, Key::StartupFormats) => "支持.charme项目文件",
        (Locale::ZhCn, Key::RecentProjects) => "最近打开的项目",
        (Locale::ZhCn, Key::ProjectFallback) => "Charme项目",
        (Locale::ZhCn, Key::Scene) => "场景",
        (Locale::ZhCn, Key::EmptyScene) => "尚未导入角色\n\n请点击“导入PMX”开始。",
        (Locale::ZhCn, Key::Materials) => "材质槽",
        (Locale::ZhCn, Key::EmptyMaterials) => "暂无材质槽",
        (Locale::ZhCn, Key::Inspector) => "检查器",
        (Locale::ZhCn, Key::InspectorBody) => "打开文件后，这里将显示材质和Shader参数。",
        (Locale::ZhCn, Key::Brightness) => "视口亮度",
        (Locale::ZhCn, Key::RendererStarting) => "正在初始化渲染器…",
        (Locale::ZhCn, Key::ProjectOpened) => "项目已打开",
        (Locale::ZhCn, Key::WaitingCharacter) => "等待角色模型…",
        (Locale::ZhCn, Key::LoadingMaterials) => "正在加载材质槽…",
        (Locale::ZhCn, Key::LoadingPmxTextures) => "正在加载PMX和纹理…",
        (Locale::ZhCn, Key::InspectingShader) => "正在检查Shader…",
        (Locale::ZhCn, Key::ShaderError) => "Shader错误",
        (Locale::ZhCn, Key::ReflectionFailed) => "WGSL反射失败",
        (Locale::ZhCn, Key::MaterialInspector) => "材质检查器",
        (Locale::ZhCn, Key::WgslShader) => "WGSLShader",
        (Locale::ZhCn, Key::NoMaterials) => "没有材质槽",
        (Locale::ZhCn, Key::ErrorPrefix) => "错误：",
        (Locale::ZhCn, Key::ChooseProjectMessage) => "选择一个.charme项目文件。",
        (Locale::ZhCn, Key::ChoosePmxMessage) => "选择一个PMX角色模型导入当前项目。",
        (Locale::ZhCn, Key::ChooseShaderMessage) => "选择一个WGSL材质Shader进行检查。",
        (Locale::ZhCn, Key::FileMenu) => "文件",
        (Locale::ZhCn, Key::OpenProjectMenu) => "打开项目…",
        (Locale::ZhCn, Key::NewProjectMenu) => "新建项目",
        (Locale::ZhCn, Key::ImportPmxMenu) => "导入PMX…",
        (Locale::ZhCn, Key::InspectShaderMenu) => "检查WGSLShader…",
        (Locale::ZhCn, Key::EditMenu) => "编辑",
        (Locale::ZhCn, Key::ViewMenu) => "视图",
        (Locale::ZhCn, Key::WindowMenu) => "窗口",
    }
}
