[package]
name = "charme-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
charme-core = { path = "../charme-core" }
charme-renderer = { path = "../charme-renderer" }
charme-shader = { path = "../charme-shader" }
thiserror.workspace = true

[lints]
workspace = true
